# Generated by Django 5.2.16 on 2026-07-12 22:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('base_url', models.URLField(max_length=2000, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('probation', 'Пробный режим'), ('probation_waiting', 'Ожидает оценок'), ('paused_low_yield', 'Пауза: низкая ценность'), ('paused_manual', 'Остановлен оператором'), ('blocked', 'Недоступен')], db_index=True, default='active', max_length=32)),
                ('is_auto_discovered', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10080)])),
                ('download_delay_seconds', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(60)])),
                ('use_playwright', models.BooleanField(default=False)),
                ('include_patterns', models.JSONField(blank=True, default=list)),
                ('exclude_patterns', models.JSONField(blank=True, default=list)),
                ('adapter_config', models.JSONField(blank=True, default=dict)),
                ('probation_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body_text', models.TextField()),
                ('language', models.CharField(blank=True, db_index=True, max_length=16)),
                ('author', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('simhash', models.BigIntegerField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_items',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['language', '-first_seen_at'], name='idx_news_lang_time')],
            },
        ),
        migrations.CreateModel(
            name='NewsOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=3000)),
                ('normalized_url', models.TextField(unique=True)),
                ('canonical_url', models.URLField(max_length=3000)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_method', models.CharField(max_length=32)),
                ('http_status', models.PositiveIntegerField(default=200)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='collector.newsitem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='collector.source')),
            ],
            options={
                'db_table': 'news_occurrences',
                'ordering': ['fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('positive', 'Позитивная'), ('not_positive', 'Не позитивная'), ('skipped', 'Пропущена')], max_length=16)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reason', models.TextField(blank=True)),
                ('selector_name', models.CharField(max_length=200)),
                ('selector_version', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('news_item', models.ForeignKey(db_column='news_id', on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='collector.newsitem')),
            ],
            options={
                'db_table': 'exchange_review_events',
            },
        ),
        migrations.CreateModel(
            name='SourceRuntimeState',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='runtime', serialize=False, to='collector.source')),
                ('next_run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=200)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'source_runtime_state',
            },
        ),
        migrations.CreateModel(
            name='OperatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_events', to='collector.source')),
            ],
            options={
                'db_table': 'operator_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=3000)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_domains', to='collector.reviewevent')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.source')),
            ],
            options={
                'db_table': 'discovery_domains',
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_runs', to='collector.source')),
            ],
            options={
                'db_table': 'crawl_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rss', 'RSS/Atom'), ('sitemap', 'Sitemap'), ('html', 'HTML-раздел')], max_length=16)),
                ('url', models.URLField(max_length=2000)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('etag', models.TextField(blank=True)),
                ('last_modified', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='collector.source')),
            ],
            options={
                'db_table': 'source_endpoints',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutboundLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=3000)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('is_external', models.BooleanField(default=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='collector.newsoccurrence')),
            ],
            options={
                'db_table': 'outbound_links',
                'indexes': [models.Index(fields=['domain', 'is_external'], name='idx_link_domain_external')],
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'url'), name='uq_occurrence_link')],
            },
        ),
        migrations.AddIndex(
            model_name='reviewevent',
            index=models.Index(fields=['news_item', 'selector_name', '-created_at'], name='idx_review_latest'),
        ),
        migrations.AddConstraint(
            model_name='reviewevent',
            constraint=models.UniqueConstraint(fields=('selector_name', 'idempotency_key'), name='uq_review_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='reviewevent',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 1)), _connector='OR'), name='ck_review_score'),
        ),
        migrations.AddIndex(
            model_name='newsoccurrence',
            index=models.Index(fields=['source', '-fetched_at'], name='idx_occ_source_time'),
        ),
        migrations.AddConstraint(
            model_name='discoverydomain',
            constraint=models.UniqueConstraint(fields=('review_event', 'domain'), name='uq_discovery_review_domain'),
        ),
        migrations.AddIndex(
            model_name='crawlrun',
            index=models.Index(fields=['source', '-started_at'], name='idx_runs_source_time'),
        ),
        migrations.AddIndex(
            model_name='sourceendpoint',
            index=models.Index(fields=['source', 'enabled', 'priority'], name='idx_endpoint_schedule'),
        ),
        migrations.AddConstraint(
            model_name='sourceendpoint',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='uq_source_endpoint_url'),
        ),
    ]
