# Generated by Django 5.2.16 on 2026-07-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_evaluation_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEvaluationScore',
            fields=[
                ('pk', models.CompositePrimaryKey('review_event_id', 'characteristic_key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('news_id', models.IntegerField()),
                ('selector_name', models.CharField(max_length=200)),
                ('review_event_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('characteristic_key', models.CharField(max_length=64)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'exchange_latest_evaluation_scores',
                'managed': False,
            },
        ),
    ]
